add test check for pre commit hook

diff --git a/githooks/pre-commit b/githooks/pre-commit
--- a/githooks/pre-commit
+++ b/githooks/pre-commit
@@ -2,7 +2,7 @@
 
 
 echo "In pre-commit-hook"
-test_fmt() {
+check_go_fmt() {
 
     echo "checking if all go files are formatted"
     hash gofmt 2>&- || { echo >&2 "gofmt not in PATH."; exit 1; }
@@ -19,11 +19,29 @@ test_fmt() {
     fi
 }
 
+check_go_test(){
+    echo "check_go_test";
+	
+	some_failed=0
+	for s in $(go list ./...); 
+		do 
+			if ! go test -failfast -v -p 1 $s; then 
+				echo "NOTOK: Test Case - $s - Failed";
+				some_failed=1;
+			fi;
+		done;
+
+	if [[ "$someFailed" -ne 0 ]]; then
+		exit 1;
+	fi
+}
+
 case "$1" in
     --about )
-        echo "Check Go code formatting"
+        echo "Checking source code"
         ;;
     * )
-        test_fmt
+        check_go_fmt
+		check_go_test
         ;;
 esac
